// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using Google.SignIn;

using Debug = System.Diagnostics.Debug;

namespace iOSTips
{
	public partial class GoogleSignInViewController : UIViewController, ISignInUIDelegate
	{
		public GoogleSignInViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			SignIn.SharedInstance.UIDelegate = this;

			SignIn.SharedInstance.SignedIn += (object sender, SignInDelegateEventArgs e) => {

				if (e.User != null && e.Error == null) {
					ToggleAuthUI ();
					Debug.WriteLine(e.User.Profile.Name);
				}
			};

			SignIn.SharedInstance.Disconnected += (object sender, SignInDelegateEventArgs e) => {

				if (e.User != null && e.Error == null) {
					ToggleAuthUI ();
					Debug.WriteLine(e.User.Profile.Name);
				}

			};

			SignIn.SharedInstance.SignInUserSilently ();
			ToggleAuthUI ();
		}

		private void ToggleAuthUI ()
		{
			var message = string.Empty;

			if (SignIn.SharedInstance.CurrentUser == null || SignIn.SharedInstance.CurrentUser.Authentication == null) {
				// Not signed in
				message = "Google Sign in\niOS Demo";

			} else {
				// Signed in
				message = $"{SignIn.SharedInstance.CurrentUser.Profile.Name}";

			}

			InvokeOnMainThread (() => {

				lbStatus.Text = message;
			
			});

		}
	}
}
