// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using ZXing;
using ZXing.Mobile;

namespace iOSTips
{
	public partial class QRCodeViewController : UIViewController
	{
		public QRCodeViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			Title = "QR Code";

			btnScan.TouchUpInside += async (object sender, EventArgs e) => {
				var scanner = new ZXing.Mobile.MobileBarcodeScanner();
				var result = await scanner.Scan();

				if (result != null){
					Console.WriteLine("Scanned Barcode: " + result.Text);

					InvokeOnMainThread(()=>{

						lbResult.Text = result.Text ;

					});
				}
					
			};

		}
	}
}
