// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace iOSTips
{
	public partial class TipCellView : UITableViewCell
	{
		public TipCellView (IntPtr handle) : base (handle)
		{
		}

		public void Update(Tip tip){
			lbName.Text = tip.Name;
			lbDescription.Text = tip.Description;
		}
	}
}
