// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace iOSTips
{
	public partial class VideoDescView : UIView
	{
		public VideoDescView (IntPtr handle) : base (handle)
		{
		}
	}
}
